// packages/react/src/components/CronPanel.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import {
  COMMON_TIME_ZONES,
  CRON_SYNTAXES,
  getExpressionTokens,
  getSyntaxSpec,
  type CronSyntax,
  type FieldKey,
} from 'cron-kit-core';

import { useCronKitStyles } from '../internal/useCronKitStyles';
import { useCronState } from '../internal/useCronState';
import type { CronPanelProps, CronPanelTab } from '../types';
import { CronBuilder } from './CronBuilder';
import { CronExplain } from './CronExplain';
import { CronExpression } from './CronExpression';
import { CronNextRuns } from './CronNextRuns';
import { CronTemplates } from './CronTemplates';

const TAB_LABELS: Record<CronPanelTab, { 'zh-CN': string; 'en-US': string }> = {
  builder: { 'zh-CN': '可视化配置', 'en-US': 'Builder' },
  expression: { 'zh-CN': '表达式', 'en-US': 'Expression' },
  templates: { 'zh-CN': '常用模板', 'en-US': 'Presets' },
  explain: { 'zh-CN': '字段说明', 'en-US': 'Explanation' },
};

/**
 * 一站式 Cron 配置面板：语法切换、时区、可视化配置、表达式、模板、说明与运行时间。
 *
 * 这是对标 cron.ciding.cc 的完整体验；只想嵌进表单时用 `CronInput` 更合适。
 */
export function CronPanel(props: CronPanelProps) {
  useCronKitStyles();

  const {
    value,
    defaultValue,
    syntax: syntaxProp,
    defaultSyntax,
    onSyntaxChange,
    timeZone,
    defaultTimeZone,
    onTimeZoneChange,
    locale = 'zh-CN',
    theme = 'light',
    nextRunsCount = 5,
    onChange,
    onValidChange,
    disabled,
    className,
    style,
    activeTab: activeTabProp,
    defaultActiveTab = 'builder',
    onTabChange,
    tabs = ['builder', 'expression', 'templates', 'explain'],
    showNextRuns = true,
    showHeader = true,
    title,
    showSyntaxSwitch = true,
    syntaxes = CRON_SYNTAXES,
    showTimeZone = true,
    showSummary = true,
    flat = false,
    footer,
  } = props;

  const state = useCronState({
    value,
    defaultValue,
    syntax: syntaxProp,
    defaultSyntax,
    onSyntaxChange,
    timeZone,
    defaultTimeZone,
    onTimeZoneChange,
    locale,
    nextRunsCount,
    onChange,
    onValidChange,
  });

  const [innerTab, setInnerTab] = useState<CronPanelTab>(defaultActiveTab);
  const tab = activeTabProp ?? innerTab;

  // 当前正在编辑的字段，用于在表达式栏高亮对应片段
  const [activeField, setActiveField] = useState<FieldKey>(
    () => getSyntaxSpec(syntaxProp ?? defaultSyntax ?? 'quartz').fields[0],
  );
  const expressionTokens = useMemo(
    () => getExpressionTokens(state.expression, state.syntax, locale),
    [state.expression, state.syntax, locale],
  );

  // 切换语法后，原字段可能不存在于新语法（如 Linux 没有「秒」），回落到第一个字段
  useEffect(() => {
    const keys = getSyntaxSpec(state.syntax).fields;
    setActiveField((current) => (keys.includes(current) ? current : keys[0]));
  }, [state.syntax]);

  const selectTab = (next: CronPanelTab) => {
    setInnerTab(next);
    onTabChange?.(next);
  };

  const [copied, setCopied] = useState(false);
  const copyTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(
    () => () => {
      if (copyTimer.current) clearTimeout(copyTimer.current);
    },
    [],
  );

  const copyExpression = async () => {
    try {
      await navigator.clipboard.writeText(state.expression);
      setCopied(true);
      if (copyTimer.current) clearTimeout(copyTimer.current);
      copyTimer.current = setTimeout(() => setCopied(false), 1600);
    } catch {
      setCopied(false);
    }
  };

  const t = (zh: string, en: string) => (locale === 'en-US' ? en : zh);
  const visibleTabs = tabs.filter((item) => item in TAB_LABELS);

  return (
    <div
      className={`ck-root${flat ? '' : ' ck-panel'}${className ? ` ${className}` : ''}`}
      style={style}
      data-ck-theme={theme}
    >
      {showHeader ? (
        <div className="ck-header">
          {title === null ? null : (
            <div>
              <h3 className="ck-title">
                {title ?? t('Cron 表达式配置', 'Cron expression')}
              </h3>
              <p className="ck-subtitle">{getSyntaxSpec(state.syntax).description}</p>
            </div>
          )}

          <div className="ck-inline" style={{ marginLeft: title === null ? 'auto' : undefined }}>
            {showSyntaxSwitch ? (
              <div className="ck-seg" role="radiogroup" aria-label={t('表达式类型', 'Syntax')}>
                {syntaxes.map((item) => (
                  <button
                    key={item}
                    type="button"
                    role="radio"
                    aria-checked={state.syntax === item}
                    className={`ck-seg__item${state.syntax === item ? ' is-active' : ''}`}
                    disabled={disabled}
                    onClick={() => state.setSyntax(item as CronSyntax)}
                  >
                    {getSyntaxSpec(item).label}
                  </button>
                ))}
              </div>
            ) : null}

            {showTimeZone ? (
              <select
                className="ck-select"
                value={state.timeZone}
                disabled={disabled}
                aria-label={t('时区', 'Time zone')}
                onChange={(event) => state.setTimeZone(event.target.value)}
              >
                {COMMON_TIME_ZONES.some((item) => item.value === state.timeZone) ? null : (
                  <option value={state.timeZone}>{state.timeZone}</option>
                )}
                {COMMON_TIME_ZONES.map((item) => (
                  <option key={item.value} value={item.value}>
                    {item.label}
                  </option>
                ))}
              </select>
            ) : null}
          </div>
        </div>
      ) : null}

      <div className="ck-expr">
        {expressionTokens.length > 0 ? (
          <div className="ck-expr__tokens">
            {expressionTokens.map((token) => {
              const active = token.key === activeField;
              return (
                <button
                  key={token.key}
                  type="button"
                  className={`ck-token${active ? ' is-active' : ''}`}
                  aria-pressed={active}
                  disabled={disabled}
                  title={`编辑「${token.label}」字段`}
                  onClick={() => {
                    setActiveField(token.key);
                    if (tab !== 'builder' && visibleTabs.includes('builder')) selectTab('builder');
                  }}
                >
                  <span className="ck-token__value">{token.value}</span>
                  <span className="ck-token__label">{token.label}</span>
                </button>
              );
            })}
          </div>
        ) : (
          <span className={`ck-expr__value${state.expression ? '' : ' is-empty'}`}>
            {state.expression || t('尚未填写表达式', 'No expression yet')}
          </span>
        )}

        <button
          type="button"
          className="ck-btn ck-btn--sm"
          onClick={copyExpression}
          disabled={disabled || !state.expression}
        >
          {copied ? t('已复制', 'Copied') : t('复制', 'Copy')}
        </button>
      </div>

      {showSummary && state.parsed.valid && state.described.summary ? (
        <div className="ck-summary ck-summary--bar">
          <span className="ck-summary__icon" aria-hidden="true">
            ↳
          </span>
          <span>{state.described.summary}</span>
        </div>
      ) : null}

      <div className="ck-main">
        <div className="ck-col">
          {visibleTabs.length > 1 ? (
            <div className="ck-tabs" role="tablist">
              {visibleTabs.map((item) => (
                <button
                  key={item}
                  type="button"
                  role="tab"
                  aria-selected={tab === item}
                  className={`ck-tabs__item${tab === item ? ' is-active' : ''}`}
                  disabled={disabled}
                  onClick={() => selectTab(item)}
                >
                  {TAB_LABELS[item][locale === 'en-US' ? 'en-US' : 'zh-CN']}
                </button>
              ))}
            </div>
          ) : null}

          {tab === 'builder' ? (
            <CronBuilder
              value={state.expression}
              syntax={state.syntax}
              locale={locale}
              theme={theme}
              disabled={disabled}
              layout="tabs"
              activeField={activeField}
              onActiveFieldChange={setActiveField}
              onChange={(next) => state.setExpression(next)}
            />
          ) : null}

          {tab === 'expression' ? (
            <CronExpression
              value={state.expression}
              syntax={state.syntax}
              locale={locale}
              disabled={disabled}
              onChange={(next) => state.setExpression(next)}
            />
          ) : null}

          {tab === 'templates' ? (
            <CronTemplates
              value={state.expression}
              syntax={state.syntax}
              locale={locale}
              onSelect={(next) => state.setExpression(next)}
            />
          ) : null}

          {tab === 'explain' ? (
            <CronExplain value={state.expression} syntax={state.syntax} locale={locale} />
          ) : null}
        </div>

        {showNextRuns ? (
          <div className="ck-col">
            <CronNextRuns
              value={state.expression}
              syntax={state.syntax}
              timeZone={state.timeZone}
              locale={locale}
              count={nextRunsCount}
            />
          </div>
        ) : null}
      </div>

      {footer}
    </div>
  );
}

// packages/vue/src/components/CronPanel.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import {
  COMMON_TIME_ZONES,
  CRON_SYNTAXES,
  getExpressionTokens,
  getSyntaxSpec,
  type CronLocale,
  type CronSyntax,
  type FieldKey,
} from 'cron-kit-core';

import { useCronState } from '../internal/useCronState';
import type { CronChangeInfo, CronPanelTab } from '../types';
import CronBuilder from './CronBuilder.vue';
import CronExplain from './CronExplain.vue';
import CronExpression from './CronExpression.vue';
import CronNextRuns from './CronNextRuns.vue';
import CronTemplates from './CronTemplates.vue';

const TAB_LABELS: Record<CronPanelTab, { 'zh-CN': string; 'en-US': string }> = {
  builder: { 'zh-CN': '可视化配置', 'en-US': 'Builder' },
  expression: { 'zh-CN': '表达式', 'en-US': 'Expression' },
  templates: { 'zh-CN': '常用模板', 'en-US': 'Presets' },
  explain: { 'zh-CN': '字段说明', 'en-US': 'Explanation' },
};

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    value?: string;
    defaultValue?: string;
    syntax?: CronSyntax;
    defaultSyntax?: CronSyntax;
    timeZone?: string;
    defaultTimeZone?: string;
    locale?: CronLocale;
    theme?: 'light' | 'dark' | 'auto';
    nextRunsCount?: number;
    disabled?: boolean;
    activeTab?: CronPanelTab;
    tabs?: CronPanelTab[];
    showNextRuns?: boolean;
    showHeader?: boolean;
    title?: string | null;
    showSyntaxSwitch?: boolean;
    syntaxes?: CronSyntax[];
    showTimeZone?: boolean;
    showSummary?: boolean;
    flat?: boolean;
  }>(),
  {
    locale: 'zh-CN',
    theme: 'light',
    nextRunsCount: 5,
    disabled: false,
    tabs: () => ['builder', 'expression', 'templates', 'explain'] as CronPanelTab[],
    showNextRuns: true,
    showHeader: true,
    showSyntaxSwitch: true,
    syntaxes: () => [...CRON_SYNTAXES] as CronSyntax[],
    showTimeZone: true,
    showSummary: true,
    flat: false,
  },
);

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
  (e: 'change', expression: string, info: CronChangeInfo): void;
  (e: 'validChange', valid: boolean): void;
  (e: 'syntaxChange', syntax: CronSyntax): void;
  (e: 'timeZoneChange', timeZone: string): void;
  (e: 'tabChange', tab: CronPanelTab): void;
}>();

const { syntax, timeZone, expression, parsed, described, setExpression, setSyntax, setTimeZone } =
  useCronState(props, emit);

const innerTab = ref<CronPanelTab>(props.activeTab ?? 'builder');
const tab = computed(() => props.activeTab ?? innerTab.value);
const visibleTabs = computed(() => props.tabs.filter((item) => item in TAB_LABELS));

// 当前正在编辑的字段，用于在表达式栏高亮对应片段
const activeField = ref<FieldKey>(getSyntaxSpec(syntax.value).fields[0]);
const expressionTokens = computed(() =>
  getExpressionTokens(expression.value, syntax.value, props.locale),
);

// 切换语法后，原字段可能不存在于新语法（如 Linux 没有「秒」），回落到第一个字段
watch(syntax, (next) => {
  const keys = getSyntaxSpec(next).fields;
  if (!keys.includes(activeField.value)) activeField.value = keys[0];
});

function focusField(key: FieldKey) {
  activeField.value = key;
  if (tab.value !== 'builder' && visibleTabs.value.includes('builder')) selectTab('builder');
}

const copied = ref(false);
let timer: ReturnType<typeof setTimeout> | null = null;
onMounted(() => {
  /* 预留：如需挂载后聚焦可在此处理 */
});
onBeforeUnmount(() => {
  if (timer) clearTimeout(timer);
});

async function copyExpression() {
  try {
    await navigator.clipboard.writeText(expression.value);
    copied.value = true;
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      copied.value = false;
    }, 1600);
  } catch {
    copied.value = false;
  }
}

function selectTab(next: CronPanelTab) {
  innerTab.value = next;
  emit('tabChange', next);
}

const t = (zh: string, en: string) => (props.locale === 'en-US' ? en : zh);
const syntaxList = computed(() => props.syntaxes);
const timeZoneList = computed(() => COMMON_TIME_ZONES);
const syntaxSpec = computed(() => getSyntaxSpec(syntax.value));
</script>

<template>
  <div class="ck-root" :class="{ 'ck-panel': !flat }" :data-ck-theme="theme">
    <div v-if="showHeader" class="ck-header">
      <div v-if="title !== null">
        <h3 class="ck-title">{{ title ?? t('Cron 表达式配置', 'Cron expression') }}</h3>
        <p class="ck-subtitle">{{ syntaxSpec.description }}</p>
      </div>

      <div class="ck-inline" :style="{ marginLeft: title === null ? 'auto' : undefined }">
        <div v-if="showSyntaxSwitch" class="ck-seg" role="radiogroup">
          <button
            v-for="item in syntaxList"
            :key="item"
            type="button"
            role="radio"
            :aria-checked="syntax === item"
            class="ck-seg__item"
            :class="{ 'is-active': syntax === item }"
            :disabled="disabled"
            @click="setSyntax(item)"
          >
            {{ getSyntaxSpec(item).label }}
          </button>
        </div>

        <select
          v-if="showTimeZone"
          class="ck-select"
          :value="timeZone"
          :disabled="disabled"
          :aria-label="t('时区', 'Time zone')"
          @change="setTimeZone(($event.target as HTMLSelectElement).value)"
        >
          <option v-if="!timeZoneList.some((item) => item.value === timeZone)" :value="timeZone">
            {{ timeZone }}
          </option>
          <option v-for="item in timeZoneList" :key="item.value" :value="item.value">
            {{ item.label }}
          </option>
        </select>
      </div>
    </div>

    <div class="ck-expr">
      <div v-if="expressionTokens.length" class="ck-expr__tokens">
        <button
          v-for="token in expressionTokens"
          :key="token.key"
          type="button"
          class="ck-token"
          :class="{ 'is-active': token.key === activeField }"
          :aria-pressed="token.key === activeField"
          :disabled="disabled"
          :title="`编辑「${token.label}」字段`"
          @click="focusField(token.key)"
        >
          <span class="ck-token__value">{{ token.value }}</span>
          <span class="ck-token__label">{{ token.label }}</span>
        </button>
      </div>
      <span v-else class="ck-expr__value" :class="{ 'is-empty': !expression }">
        {{ expression || t('尚未填写表达式', 'No expression yet') }}
      </span>

      <button
        type="button"
        class="ck-btn ck-btn--sm"
        :disabled="disabled || !expression"
        @click="copyExpression"
      >
        {{ copied ? t('已复制', 'Copied') : t('复制', 'Copy') }}
      </button>
    </div>

    <div v-if="showSummary && parsed.valid && described.summary" class="ck-summary ck-summary--bar">
      <span class="ck-summary__icon" aria-hidden="true">↳</span>
      <span>{{ described.summary }}</span>
    </div>

    <div class="ck-main">
      <div class="ck-col">
        <div v-if="visibleTabs.length > 1" class="ck-tabs" role="tablist">
          <button
            v-for="item in visibleTabs"
            :key="item"
            type="button"
            role="tab"
            :aria-selected="tab === item"
            class="ck-tabs__item"
            :class="{ 'is-active': tab === item }"
            :disabled="disabled"
            @click="selectTab(item)"
          >
            {{ TAB_LABELS[item][locale === 'en-US' ? 'en-US' : 'zh-CN'] }}
          </button>
        </div>

        <CronBuilder
          v-if="tab === 'builder'"
          :model-value="expression"
          :syntax="syntax"
          :locale="locale"
          :theme="theme"
          :disabled="disabled"
          layout="tabs"
          :active-field="activeField"
          @update:model-value="setExpression"
          @active-field-change="activeField = $event"
        />

        <CronExpression
          v-else-if="tab === 'expression'"
          :model-value="expression"
          :syntax="syntax"
          :locale="locale"
          :theme="theme"
          :disabled="disabled"
          @update:model-value="setExpression"
        />

        <CronTemplates
          v-else-if="tab === 'templates'"
          :model-value="expression"
          :syntax="syntax"
          :locale="locale"
          :theme="theme"
          @select="setExpression"
        />

        <CronExplain
          v-else-if="tab === 'explain'"
          :model-value="expression"
          :syntax="syntax"
          :locale="locale"
          :theme="theme"
        />
      </div>

      <div v-if="showNextRuns" class="ck-col">
        <CronNextRuns
          :model-value="expression"
          :syntax="syntax"
          :time-zone="timeZone"
          :locale="locale"
          :theme="theme"
          :count="nextRunsCount"
        />
      </div>
    </div>

    <slot />
  </div>
</template>
